name: Trivy Scan

on:
  push:
    branches:
      - main

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Trivy scan on Docker images from Docker Hub
        run: |
          # Replace 'nginx' with the name of the Docker image you want to scan
          docker pull nginx
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy nginx > nginx_scan_report.txt

          # You can repeat the above steps for other Docker images from Docker Hub
          # For example:
          # docker pull alpine
          # docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy alpine > alpine_scan_report.txt

      - name: Save Trivy reports as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: trivy-scan-reports
          # Adjust the paths to include all the scan reports you want to save as artifacts
          path: |
            nginx_scan_report.txt
            # Add more paths for additional scan reports if needed
