name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  # You can add additional triggers here, such as pull requests

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build --tag aindi123/simplecs:latest .

    - name: Log in to DockerHub
      run: docker login -u ${{ secrets.aindi123 }} -p ${{ secrets.dckr_pat_AD0J4Za04kaneKx8_tejN10Pjz0 }}

    - name: Push Docker image
      run: docker push aindi123/samplecs:latest
