name: Trivy Scan

on:
  push:
    branches:
      - main

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Trivy scan on Docker images from Docker Hub
        run: |
          docker pull nginx
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image nginx > nginx_scan_report.txt

      - name: Save Trivy reports as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: trivy-scan-reports
          # Adjust the paths to include all the scan reports you want to save as artifacts
          path: |
            nginx_scan_report.txt
